model_name: meta-llama/Llama-3.2-1B
sentence_transformer_model: BAAI/bge-m3
experiment_name: temp-testing
checkpoint_path: pt_models
graph_path: data/gnd.pickle
dataset_path: datasets/no_context
num_epochs: 10
batch_size: 32
learning_rate: 0.01
warmup_rate: 0.0
max_grad_norm: 1.0
eval_steps: 100
logging_steps: 50
save_steps: 5000
eval_generation: true
train_subsample_ratio: 1.0
validate_subsample_ratio: 0.03
sort_by_freq: true
use_k_freq_labels: 0
learning_rate_decay: False

context:
  context_type: null # Choices: "text" or "graph". Use null if no context is needed.
  top_k: 0 # How many instances to retrieve
  hops: 0 # Also include hops in the knowledge graph from retrieved instances
  title_wise: false # Whether to retrieve title-to-label or title-to-title
  relation: null # Choices: null (use all relations) "broader" or "related"
  index_path: "data/label_index.pkl"
  mapping_path: "data/label_mapping.pkl"

prompt_config:
  num_prompt_tokens: 150
  at_layer: -1 # -1 is at input embeddings.
  hidden_size: 2048
  down_project_size: 1024
  dropout: 0.05
  type: "random" # Choices: "hidden_states", "random" or "context"